import { GradeLevel, LessonType, PaymentCycle } from '../types';

export interface ParsedScheduleSlot {
  day: string;
  time: string;
}

export interface ParsedGroupData {
  name: string;
  grade: GradeLevel;
  type: LessonType;
  days: string[];
  time: string; // Default or first schedule time
  schedules: ParsedScheduleSlot[];
  dayTimes: Record<string, string>;
  payment_type: PaymentCycle;
  payment_amount: number;
  lesson_price?: number;
}

export interface ParsedStudentData {
  name: string;
  phone: string;
}

export interface AiImportResult {
  isValid: boolean;
  group: ParsedGroupData | null;
  students: ParsedStudentData[];
  errors: string[];
  warnings: string[];
}

const SAMPLE_IMPORT_TEMPLATE = `[GROUP]
name=Grade 5 A
grade=Grade 5
type=offline
days=Sunday,Wednesday
time=18:00
payment_type=every_4_lessons
payment_amount=400

[STUDENTS]
Ahmed Mohamed|01012345678
Mohamed Ali|01112345679
Mariam Hassan|01212345670`;

const SAMPLE_MULTI_SCHEDULE_TEMPLATE = `[GROUP]
name=Grade 10 Physics
grade=Grade 10
type=offline
lesson_price=150
payment_type=every_8_lessons

[SCHEDULE]
Saturday|15:00
Wednesday|19:00

[STUDENTS]
Omar Farouk|01098765432
Nour El Din|01123456789
Youssef Ahmed|01234567890`;

export { SAMPLE_IMPORT_TEMPLATE, SAMPLE_MULTI_SCHEDULE_TEMPLATE };

/**
 * Normalizes grade strings into valid GradeLevel values
 */
function normalizeGrade(rawGrade: string): GradeLevel {
  const trimmed = rawGrade.trim();
  if (trimmed.startsWith('Grade ')) {
    return trimmed as GradeLevel;
  }
  const match = trimmed.match(/\d+/);
  if (match) {
    const num = parseInt(match[0], 10);
    if (num >= 1 && num <= 12) {
      return `Grade ${num}` as GradeLevel;
    }
  }
  return 'Grade 5';
}

/**
 * Validates HH:MM format (e.g., "18:00", "09:30", "9:30")
 */
function isValidTimeStr(timeStr: string): boolean {
  if (!timeStr) return false;
  const timeRegex = /^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$/;
  return timeRegex.test(timeStr.trim());
}

/**
 * Normalizes time string to standard HH:MM format (e.g., "9:30" -> "09:30")
 */
function normalizeTimeStr(timeStr: string): string {
  const trimmed = timeStr.trim();
  const parts = trimmed.split(':');
  if (parts.length === 2) {
    const h = parts[0].padStart(2, '0');
    const m = parts[1].padStart(2, '0');
    return `${h}:${m}`;
  }
  return trimmed;
}

/**
 * Parses and strictly validates AI-generated import text according to ZERO-DATA-LOSS specifications.
 */
export function parseAiImportText(text: string): AiImportResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!text || !text.trim()) {
    return {
      isValid: false,
      group: null,
      students: [],
      errors: ['Import text is empty. Please paste the template generated by AI.'],
      warnings: [],
    };
  }

  const rawLines = text.split('\n');

  // Locate sections
  let groupSectionStartIndex = -1;
  let scheduleSectionStartIndex = -1;
  let studentsSectionStartIndex = -1;

  for (let i = 0; i < rawLines.length; i++) {
    const lineUpper = rawLines[i].trim().toUpperCase();
    if (lineUpper === '[GROUP]') {
      groupSectionStartIndex = i;
    } else if (lineUpper === '[SCHEDULE]' || lineUpper === '[TIMINGS]') {
      scheduleSectionStartIndex = i;
    } else if (lineUpper === '[STUDENTS]') {
      studentsSectionStartIndex = i;
    }
  }

  if (groupSectionStartIndex === -1) {
    errors.push('Missing [GROUP] section header in the pasted text.');
  }

  if (studentsSectionStartIndex === -1) {
    errors.push('Missing [STUDENTS] section header in the pasted text.');
  }

  if (errors.length > 0) {
    return {
      isValid: false,
      group: null,
      students: [],
      errors,
      warnings,
    };
  }

  // Helper to slice lines belonging to a section until the next section
  const sectionIndices = [
    { name: 'group', idx: groupSectionStartIndex },
    { name: 'schedule', idx: scheduleSectionStartIndex },
    { name: 'students', idx: studentsSectionStartIndex },
  ]
    .filter((s) => s.idx !== -1)
    .sort((a, b) => a.idx - b.idx);

  const getSectionLines = (sectionName: string): string[] => {
    const secObj = sectionIndices.find((s) => s.name === sectionName);
    if (!secObj) return [];
    const currentPos = sectionIndices.indexOf(secObj);
    const start = secObj.idx + 1;
    const end = currentPos + 1 < sectionIndices.length ? sectionIndices[currentPos + 1].idx : rawLines.length;
    return rawLines.slice(start, end);
  };

  const groupLines = getSectionLines('group');
  const scheduleLines = getSectionLines('schedule');
  const studentLines = getSectionLines('students');

  // Parse [GROUP] key-value pairs
  const groupKv: Record<string, string> = {};
  for (const line of groupLines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('//')) {
      continue;
    }
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx !== -1) {
      const key = trimmed.substring(0, eqIdx).trim().toLowerCase();
      const val = trimmed.substring(eqIdx + 1).trim();
      if (key) {
        groupKv[key] = val;
      }
    }
  }

  // Validate GROUP basic fields
  const name = groupKv['name'] || '';
  const rawGrade = groupKv['grade'] || '';
  const rawType = (groupKv['type'] || '').toLowerCase();
  const rawDaysKey = groupKv['days'] || '';
  const rawScheduleKey = groupKv['schedule'] || groupKv['timings'] || '';
  const rawTimeKey = groupKv['time'] || groupKv['default_time'] || '';

  if (!name.trim()) {
    errors.push('Group "name" field is required in [GROUP] section.');
  }

  if (!rawGrade.trim()) {
    errors.push('Group "grade" field is required in [GROUP] section.');
  }

  if (!rawType.trim()) {
    errors.push('Group "type" field is required in [GROUP] section (accepted: online, offline).');
  } else if (rawType !== 'online' && rawType !== 'offline') {
    errors.push(`Invalid group "type" "${rawType}". Must be either "online" or "offline".`);
  }

  // Parse Schedule Slots
  const parsedSchedules: ParsedScheduleSlot[] = [];
  const parsedDaysSet = new Set<string>();
  const dayTimesMap: Record<string, string> = {};

  // Strategy A: Parse dedicated [SCHEDULE] section if present
  if (scheduleLines.length > 0) {
    for (let i = 0; i < scheduleLines.length; i++) {
      const line = scheduleLines[i].trim();
      if (!line || line.startsWith('#') || line.startsWith('//')) continue;

      let dayStr = '';
      let timeStr = '';

      if (line.includes('|')) {
        const parts = line.split('|');
        dayStr = parts[0].trim();
        timeStr = parts[1].trim();
      } else if (line.includes('@')) {
        const parts = line.split('@');
        dayStr = parts[0].trim();
        timeStr = parts[1].trim();
      } else if (line.includes(':') && !isValidTimeStr(line)) {
        // e.g. "Saturday: 15:00" -> split on first colon
        const cIdx = line.indexOf(':');
        dayStr = line.substring(0, cIdx).trim();
        timeStr = line.substring(cIdx + 1).trim();
      } else {
        // Space separated, e.g. "Saturday 15:00"
        const spaceIdx = line.lastIndexOf(' ');
        if (spaceIdx !== -1) {
          dayStr = line.substring(0, spaceIdx).trim();
          timeStr = line.substring(spaceIdx + 1).trim();
        }
      }

      if (!dayStr) {
        errors.push(`Invalid schedule line "${line}" in [SCHEDULE] block. Missing day name.`);
        continue;
      }

      if (!isValidTimeStr(timeStr)) {
        errors.push(`Invalid time format "${timeStr}" for day "${dayStr}" in [SCHEDULE]. Expected HH:MM format (e.g. 15:00).`);
        continue;
      }

      const formattedTime = normalizeTimeStr(timeStr);
      parsedSchedules.push({ day: dayStr, time: formattedTime });
      parsedDaysSet.add(dayStr);
      dayTimesMap[dayStr] = formattedTime;
    }
  }

  // Strategy B: If no [SCHEDULE] section, check `schedule=` or `days=` key in [GROUP]
  if (parsedSchedules.length === 0) {
    const scheduleKeyValue = rawScheduleKey || rawDaysKey;

    if (scheduleKeyValue) {
      // Check if scheduleKeyValue has day@time pairs e.g. "Saturday@15:00,Wednesday@19:00" or "Saturday|15:00,Wednesday|19:00"
      const items = scheduleKeyValue.split(',').map((s) => s.trim()).filter(Boolean);

      for (const item of items) {
        if (item.includes('@') || item.includes('|')) {
          const sep = item.includes('@') ? '@' : '|';
          const [dStr, tStr] = item.split(sep).map((s) => s.trim());
          if (dStr && isValidTimeStr(tStr)) {
            const formattedTime = normalizeTimeStr(tStr);
            parsedSchedules.push({ day: dStr, time: formattedTime });
            parsedDaysSet.add(dStr);
            dayTimesMap[dStr] = formattedTime;
          } else {
            errors.push(`Invalid day/time format "${item}". Expected format: Day@HH:MM (e.g. Saturday@15:00).`);
          }
        } else {
          // Standard day name without inline time e.g. "Sunday", "Wednesday"
          const fallbackTime = rawTimeKey && isValidTimeStr(rawTimeKey) ? normalizeTimeStr(rawTimeKey) : '18:00';
          parsedSchedules.push({ day: item, time: fallbackTime });
          parsedDaysSet.add(item);
          dayTimesMap[item] = fallbackTime;
        }
      }
    }
  }

  // Validation checks for schedule
  if (parsedSchedules.length === 0) {
    errors.push(
      'Schedule information is required. Provide either a [SCHEDULE] block (e.g. Saturday|15:00) or "days=" and "time=" in [GROUP].'
    );
  }

  // Fallback default group time
  const primaryTime = parsedSchedules.length > 0 ? parsedSchedules[0].time : (isValidTimeStr(rawTimeKey) ? normalizeTimeStr(rawTimeKey) : '18:00');
  const parsedDays = Array.from(parsedDaysSet);

  // Parse & Calculate Payment
  const rawPaymentType = (groupKv['payment_type'] || '').toLowerCase();
  const rawPaymentAmount = groupKv['payment_amount'] || groupKv['amount'] || groupKv['package_price'] || '';
  const rawLessonPrice = groupKv['lesson_price'] || groupKv['price_per_lesson'] || groupKv['price'] || groupKv['session_price'] || '';

  const validPaymentTypes = ['per_lesson', 'every_4_lessons', 'every_8_lessons', 'monthly'];
  let mappedPaymentCycle: PaymentCycle = '4_lessons';

  if (!rawPaymentType.trim()) {
    errors.push(
      'Group "payment_type" field is required in [GROUP] section (accepted: per_lesson, every_4_lessons, every_8_lessons, monthly).'
    );
  } else if (!validPaymentTypes.includes(rawPaymentType)) {
    errors.push(
      `Invalid payment_type "${rawPaymentType}". Must be one of: per_lesson, every_4_lessons, every_8_lessons, monthly.`
    );
  } else {
    if (rawPaymentType === 'per_lesson') mappedPaymentCycle = 'per_lesson';
    else if (rawPaymentType === 'every_4_lessons') mappedPaymentCycle = '4_lessons';
    else if (rawPaymentType === 'every_8_lessons') mappedPaymentCycle = '8_lessons';
    else if (rawPaymentType === 'monthly') mappedPaymentCycle = 'monthly';
  }

  let finalPaymentAmount = 0;
  let parsedLessonPrice: number | undefined = undefined;

  if (rawLessonPrice.trim()) {
    const parsedLp = parseFloat(rawLessonPrice);
    if (!isNaN(parsedLp) && parsedLp >= 0) {
      parsedLessonPrice = parsedLp;
    } else {
      errors.push(`Invalid lesson_price "${rawLessonPrice}". Must be a non-negative number.`);
    }
  }

  if (rawPaymentAmount.trim()) {
    const parsedAmt = parseFloat(rawPaymentAmount);
    if (isNaN(parsedAmt) || parsedAmt < 0) {
      errors.push(`Invalid payment_amount "${rawPaymentAmount}". Must be a non-negative number.`);
    } else {
      finalPaymentAmount = parsedAmt;
    }
  } else if (parsedLessonPrice !== undefined) {
    // Dynamically calculate payment_amount from lesson_price based on payment_type
    if (mappedPaymentCycle === 'per_lesson') {
      finalPaymentAmount = parsedLessonPrice;
    } else if (mappedPaymentCycle === '4_lessons') {
      finalPaymentAmount = parsedLessonPrice * 4;
    } else if (mappedPaymentCycle === '8_lessons') {
      finalPaymentAmount = parsedLessonPrice * 8;
    } else if (mappedPaymentCycle === 'monthly') {
      finalPaymentAmount = parsedLessonPrice * 8; // Default 8 sessions per month
    }
  } else {
    errors.push('Payment details missing: Either "payment_amount" or "lesson_price" must be specified in [GROUP].');
  }

  // Parse [STUDENTS] section
  const parsedStudents: ParsedStudentData[] = [];
  const seenPhones = new Set<string>();
  const seenNames = new Set<string>();

  let studentLineCount = 0;

  for (let idx = 0; idx < studentLines.length; idx++) {
    const rawLine = studentLines[idx];
    const trimmedLine = rawLine.trim();

    if (!trimmedLine || trimmedLine.startsWith('#') || trimmedLine.startsWith('//')) {
      continue;
    }

    studentLineCount++;

    if (!trimmedLine.includes('|')) {
      errors.push(
        `Student line ${studentLineCount} ("${trimmedLine}") is missing the "|" pipe separator. Expected format: student_name|phone`
      );
      continue;
    }

    const parts = trimmedLine.split('|');
    const studentName = parts[0].trim();
    const studentPhone = parts.slice(1).join('|').trim();

    if (!studentName) {
      errors.push(`Student name is empty on student line ${studentLineCount}.`);
    }

    if (!studentPhone) {
      errors.push(`Phone number is empty for student "${studentName || `Line ${studentLineCount}`}".`);
    }

    if (studentName && studentPhone) {
      const lowerPhone = studentPhone.replace(/\s+/g, '');
      const lowerName = studentName.toLowerCase();

      if (seenPhones.has(lowerPhone)) {
        errors.push(
          `Duplicate phone number "${studentPhone}" detected for student "${studentName}". Duplicate phones inside same import are not allowed.`
        );
      } else {
        seenPhones.add(lowerPhone);
      }

      if (seenNames.has(lowerName)) {
        errors.push(
          `Duplicate student name "${studentName}" detected in the import list. Duplicate student names inside same import are not allowed.`
        );
      } else {
        seenNames.add(lowerName);
      }

      parsedStudents.push({
        name: studentName,
        phone: studentPhone,
      });
    }
  }

  if (studentLineCount === 0) {
    errors.push('At least one student record is required in the [STUDENTS] section.');
  }

  const isValid = errors.length === 0;

  const groupData: ParsedGroupData | null =
    isValid || (name && rawGrade && rawType)
      ? {
          name: name.trim(),
          grade: normalizeGrade(rawGrade),
          type: (rawType === 'online' ? 'online' : 'offline') as LessonType,
          days: parsedDays,
          time: primaryTime,
          schedules: parsedSchedules,
          dayTimes: dayTimesMap,
          payment_type: mappedPaymentCycle,
          payment_amount: finalPaymentAmount,
          lesson_price: parsedLessonPrice,
        }
      : null;

  return {
    isValid,
    group: groupData,
    students: parsedStudents,
    errors,
    warnings,
  };
}
